server:
  port: 8080

spring:
  rabbitmq:
    addresses: 192.168.151.137:5672, 192.168.151.138:5672, 192.168.151.139:5672
    username: admin
    password: admin
    virtual-host: admin
    connection-timeout: 5000
    # 生产端配置, 启用消息发送确认模式
    publisher-confirm-type: simple
    # 发送失败退回, 注意需要和 mandatory 配合一起使用
    publisher-returns: true
    # 发送失败退回后回调
    template:
      mandatory: true
    listener:
      simple:
        # 手动 ack 确保消息被消费端消费
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 5
        # 批量消息消费
        prefetch: 1




